"use client";

import { poppins } from "../../lib/font.js";
import "./globals.css";
import Navbar from "../../components/Navbar.js";
import Footer from "../../components/Footer.js";
import PageTransition from "../../components/PageTransition.js";
import { usePageTransition } from "../../hooks/usePageTransition.js";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function RootLayoutClient({ children }) {
  const { isLoading } = usePageTransition()
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
      <PageTransition isLoading={isLoading}>
      <Navbar />
        {children}
        <Footer />
        </PageTransition>
        </body>
    </html>
  );
}

export default function RootLayout({ children }) {
  return <RootLayoutClient>{children}</RootLayoutClient>
}
